name: CI

on:
  push:
    branches:
      - main

jobs:
  directories:
    runs-on: self-hosted
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }}
    steps:
      - uses: actions/checkout@v3

      - id: set-dirs
        run: echo "::set-output name=dir::$(ls -d */ | sed 's/\/$//' | jq -R -s -c 'split("\n")[:-1]')"

      - name: print dirs
        run: echo ${{ steps.set-dirs.outputs.dir }}

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    needs: [ directories ]
    strategy:
      matrix:
        path: ${{fromJson(needs.directories.outputs.dir)}}
    defaults:
      run:
        working-directory: ${{ matrix.path }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: rajattomar/${{ matrix.path }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: See docker context
        run: docker context ls

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: true
