name: CI

on:
  push:
    branches:
      - main

jobs:
  directories:
    runs-on: self-hosted
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }}
    steps:
      - uses: actions/checkout@v3

      - id: set-dirs
        run: echo "::set-output name=dir::$(ls -d */ | sed 's/\/$//' | jq -R -s -c 'split("\n")[:-1]')"

      - name: print dirs
        run: echo ${{ steps.set-dirs.outputs.dir }}

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    needs: [ directories ]
    strategy:
      matrix:
        path: ${{fromJson(needs.directories.outputs.dir)}}
    defaults:
      run:
        working-directory: ${{ matrix.path }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build --no-cache -t ${{ github.repository }}:${{ matrix.path }} .
